version: '3.7'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"  
    volumes:
      - .:/app
    depends_on:
      - mysql

  backend:
    build:
      context: ./Login 
    ports:
      - "80:80"  

  mysql:

    build: ./init-scripts
    container_name: contenedor-mysql

volumes:
  mysql-data:



