export const JUEGOS_PHP = 'http://localhost/mostrar.php'; //mostrar juegos
export const REGISTRO ='http://localhost/Registro.php';//registro
export const LOGIN = 'http://localhost/IniciarSesion.php';//Iniciar sesión
export const ENVIAR_COMENT = 'http://localhost/Comentarios.php';//Enviar comentario
export const JUEGOS_CARRO_PHP = 'http://localhost/MostrarCarrito.php'; //Mostrar el carrito
export const AÑADIR_CARRITO = 'http://localhost/addCarrito.php'; //Añadir al carrito
export const Aumentar_Decrementar='http://localhost/aumentarDecre.php';//aumentar unidades
export const ELIMINAR_DEL_CARRITO='http://localhost/ElminarDelCarrito.php';//Eliminar del carrito
export const MOSTRAR_DATOS_USUARIO='http://localhost/mostrarDatosUsuario.php'; //Mostrar los datos del usuario
export const MOSTRAR_INVENTARIO='http://localhost/MostrarInvetario.php';//Mostrar el inventario 
export const PERFIL='http://localhost/Perfil.php';//Perfil del usuario
export const ACTUALIZAR_RUTA_IMAGEN='http://localhost/avatares/'; //Actualizar ruta de la imagen
export const ELIMINAR_IMAGEN='http://localhost/EliminarImagen.php';//Eliminar imagen
export const VALORAR_JUEGO='http://localhost/ValorarJuego.php';//valorar juego
export const ELMINAR_CATEGORIA_JUEGO='http://localhost/EliminarCategoriaJuego.php';//Eliminar categoria de un juego
export const ELMINAR_IMAGEN_CARROUSEL='http://localhost/EliminarImagenCarrousel.php';//Eliminar imagene del carrousel de un juego
export const INVENTARIO_USUARIO='http://localhost/InventarioUsuario.php';//Inventario del usuario
export const MOSTRAR_COMENTARIOS='http://localhost/MostrarComentario.php';//Mostrar los comentarios
export const ELIMINAR_COMENTARIOS='http://localhost/EliminarComentario.php';//Eliminar comentarios
export const EDITAR_COMENTARIOS='http://localhost/EditarComentario.php';//Editar comentarios
export const VALORAR_COMENTARIOS='http://localhost/ValoracionComentatio.php';//valorar comentario
export const INSERTAR_IMAGEN_CARROUSEL='http://localhost/InsertarCarrousel.php';//insertar imagenes en el carrousel
export const INSERTAR_JUEGO='http://localhost/insert.php';//insertat juegos
export const OBTENER_CATEGORIA='http://localhost/obtenerCategorias.php';//obtener categorias 
export const INSERTAR_CATEGORIA='http://localhost/insertCat.php';//insertar categorias en un juego
export const INSERTAR_CATEGORIA_2='http://localhost/insertarCategoria.php';//insertar categorias
export const ELIMINAR_CATEGORIA='http://localhost/EliminarCategoria.php';//eliminar categoria
export const MOSTRAR_USUARIOS='http://localhost/MostrarTodosLosUsuario.php';//mostrar todos los usuarios
export const ELIMINAR_USUARIOS='http://localhost/EliminarUsuario.php';//eliminar los usuarios
export const ELIMINAR_JUEGOS='http://localhost/eliminarJuego.php';//eliminar juegos
export const EDITAR_JUEGO='http://localhost/EditarJuego.php'; //Editar juegos
export const API='http://localhost/api.php'; //Editar juegos