version: '3'
services:
  react-app:
    image: bl4cksnk/proyecto-react:latest
    ports:
      - "3001:80"  
   
    depends_on:
      - mysql 

  backend:
    image: bl4cksnk/proyecto-php:latest
    ports:
      - "80:80"  
    depends_on:
      - mysql

  mysql:
    image: bl4cksnk/proyecto-mysql:latest
   
   



